name: Deploy Laravel

on:
  push:
    branches:
      - main

jobs:
  deploy:

    runs-on: ubuntu-latest
    environment: adityakunhare 

    steps:

      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1

        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}

          script: |
            cd /home/u912768491/domains/forum.adityakunhare.com 

            git pull origin main
            
            # composer install

            php artisan migrate --force
            php artisan optimize:clear
            
            npm run build
            
            php artisan optimize

            
